### PR TITLE
unmodifiableList vs List.of

### PR DESCRIPTION
**Pull request by krawmaciej**
I added all demonstrations as tests, mainly for checking if exceptions are thrown and checking (with Mockito) if Collections.unmodifiableList holds reference to list it was created from, and uses this list to perform operations.

Answer to question if unmodifiableList and List.of use the same classes or different:

List.of uses classes from package private `java.util.ImmutableCollections` class: 
`ImmutableCollections.List12<E>` for 1 or 2 element lists
`ImmutableCollections.ListN<E>` for other number of elements.

unmodifiableList uses package private `UnmodifiableList<E>` class from public `java.util.Collections class`.

therefore they use different classes, however these classes implement (directly or in hierarchy) List<E> so they can be returned as List<E> from `Collections.unmodifiableList()` and `List.of()` methods.

_edit: if this will be ready to be merged then I want to ask to squash merge_

### CODE REVIEW

**Comment by marcin-ogorzalek-EPAM** [comment]
Very nice solutions with tests and Mockito. When time come you just need to bump up the project's version (and maybe resolve some merge confilts). Maybe there will be need to adding your tests to `testng.xml` if it will be intoroduced.

**Comment by krawmaciej** [comment]
@marcin-ogorzalek-EPAM 
Hi! I've merged latest updates and bumped the project's version. No more conflicts with base branch :)

**Comment by marcin-ogorzalek-EPAM** [comment]
Bump up to 0.8 and I can marge it.

**Comment by marcin-ogorzalek-EPAM** [comment]
Om more remark. Please add your tests to `testng.xml`

**Comment by krawmaciej** [comment]
> One more remark. Please add your tests to `testng.xml`

@marcin-ogorzalek-EPAM Done! Conflicts resolved, test added to testng.xml, and app version bumped :)

**Comment by marcin-ogorzalek-EPAM** [comment]
I'm not a fan of splitting all dependencies with empty lines. It makes sense to split a testing and a non-testing dependencies on the groups with empty lines, but not separate all of them from each other.

**Comment by krawmaciej** [comment]
@marcin-ogorzalek-EPAM
Thank you for the advice, I removed all empty lines between dependencies.

**Pull request merged**
